swagger: '2.0'
info:
  title: e-Corner API
  description: API para o acesso às informações sobre as esquinas conectadas e inteligentes
  version: 1.0.0
host: api.e-corner.xyz
schemes:
  - http
basePath: /v1
produces:
  - application/json
paths:
  /describe:
    get:
      summary: Descreve uma esquina
      description: |
        Este endpoint retorna informações sobre uma esquina indicada pelo seu
        UUID.
      parameters:
        - name: uuid
          in: query
          description: UUID da esquina
          required: true
          type: string
          format: uuid
      tags:
        - Info
      responses:
        '200':
          description: Descrição da esquina
          schema:
            $ref: '#/definitions/Esquina'
        default:
          description: Erro inesperado
          schema:
            $ref: '#/definitions/Status'
  /putMe:
    post:
      summary: Registra presença de alguém na esquina
      description: |
        Ao chegar a uma esquina, o usuário pode informar ao serviço que está nela. Essa informação será usada, depois, para estatísticas e melhoria da qualidade do serviço
      parameters:
        - name: uuid
          in: header
          description: UUID da esquina
          required: true
          type: string
          format: uuid
        - name: user
          in: header
          description: Identificador do usuário
          required: true
          type: string
          format: email
      tags:
        - Knowledge
      responses:
        '200':
          description: Usuário registrado
          schema:
            $ref: '#/definitions/Status'
  /removeMe:
    post:
      summary: Remove alguém de uma esquina
      description: |
        Ao sair de uma esquina, o usuário pode informar ao serviço. Essa informação será usada, depois, para estatísticas e melhoria da qualidade do serviço
      parameters:
        - name: uuid
          in: header
          description: UUID da esquina
          required: true
          type: string
          format: uuid
        - name: user
          in: header
          description: Identificador do usuário
          required: true
          type: string
          format: email
      tags:
        - Knowledge
      responses:
        '200':
          description: Usuário registrado
          schema:
            $ref: '#/definitions/Status'
definitions:
  Coordenadas:
    type: object
    required:
    - latitude
    - longitude
    properties:
        latitude:
            type: number
            format: double
            description: 'Latitude do local em graus decimais (-999.999999). Valores negativos indicam coordenadas ao Sul da linha do Equador.'
        longitude:
            type: number
            format: double
            description: 'Longitude do local em graus decimais (-999.999999). Valores negativos indicam coordenadas à esquerda do meridiano de Greenwich.'
        altitude:
            type: number
            format: double
            description: 'Altitude da esquina, em metros acima do nível do mar.'
  Rua:
    type: object
    required:
    - nome
    properties:
      nome:
        type: string
        description: 'Nome da rua'
      largura:
        type: number
        format: integer
        description: 'Largura da rua, em metros'
      seguroCruzar:
        type: boolean
        description: 'Valor lógico que indica se é seguro ou não atravessar essa rua'
  Esquina:
    type: object
    properties:
      uuid:
        type: string
        format: uuid
        description: 'Identificador único da esquina'
      ruaPrincipal:
        type: object
        description: 'Rua principal do cruzamento'
        $ref: '#/definitions/Rua'
      ruaSecundaria:
        type: object
        description: 'Rua secundária do cruzamento'
        $ref: '#/definitions/Rua'
      posicao:
        $ref: '#/definitions/Coordenadas'
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
