swagger: '2.0'
info:
  title: e-Corner API
  description: API para o acesso às informações sobre as esquinas conectadas e inteligentes
  version: 1.1.0
host: api.e-corner.xyz
schemes:
  - http
basePath: /v1
consumes:
  - application/json
produces:
  - application/json
tags:
  - name: Info
    description: Chamadas que retornam/atualizam dados básicos sobre as elementos
  - name: Knowledge
    description: Chamadas que retornam/atualizam alguma informação específica sobre a entidade
paths:
  '/describe/{uuid}':
    get:
      summary: Descreve uma esquina
      description: |
        Este endpoint retorna informações sobre uma esquina indicada pelo seu
        UUID.
      parameters:
        - name: uuid
          in: path
          description: UUID da esquina
          required: true
          type: string
          format: uuid
      tags:
        - Info
      responses:
        '200':
          description: Descrição da esquina
          schema:
            $ref: '#/definitions/Esquina'
        default:
          description: Erro inesperado
          schema:
            $ref: '#/definitions/Status'
  /updateSemaphores:
    post:
      summary: Atualiza o estado do semáforo em uma rua
      description: >
        Neste endpoint, o microcontrolador na esquina pode atualizar a situação do semáforo de pedestre de uma rua em determinada esquina. Uma mesma rua pode ter várias esquinas.
      parameters:
        - name: newInfo
          in: body
          description: UUID da esquina
          required: true
          schema:
            $ref: '#/definitions/CrossingStatus'
      tags:
        - Knowledge
      responses:
        '200':
          description: Situação do semáforo atualizada
          schema:
            $ref: '#/definitions/Status'
        default:
          description: Erro inesperado
          schema:
            $ref: '#/definitions/Status'
  '/getSemaphore/{uuid}':
    get:
      summary: Obtém a situação dos semáforos em uma esquina
      description: >
        Neste endpoint, o consumidor pode obter a situação dos semáforos da esquina, bastando para isso informar o UUID da esquina. Na resposta, ele tem os UUIDs das ruas e a situação do semáforo de pedestre em cada uma delas.
      parameters:
        - name: uuid
          in: path
          description: UUID da esquina (cruzamento) da qual se deseja a situação dos semáforos
          required: true
          type: string
          format: uuid
      tags:
        - Info
      responses:
        '200':
          description: Situação dos semáforos no cruzamento
          schema:
            $ref: '#/definitions/Semaforos'
        default:
          description: Erro inesperado
          schema:
            $ref: '#/definitions/Status'
  /putMe:
    post:
      summary: Registra presença de alguém na esquina
      description: >
        Ao chegar a uma esquina, o usuário pode informar ao serviço que está
        nela. Essa informação será usada, depois, para estatísticas e melhoria da
        qualidade do serviço
      parameters:
        - name: uuid
          in: header
          description: UUID da esquina
          required: true
          type: string
          format: uuid
        - name: user
          in: header
          description: Identificador do usuário
          required: true
          type: string
          format: email
      tags:
        - Knowledge
      responses:
        '200':
          description: Usuário registrado
          schema:
            $ref: '#/definitions/Status'
        default:
          description: Erro inesperado
          schema:
            $ref: '#/definitions/Status'
  /removeMe:
    post:
      summary: Remove alguém de uma esquina
      description: >
        Ao sair de uma esquina, o usuário pode informar ao serviço. Essa
        informação será usada, depois, para estatísticas e melhoria da qualidade
        do serviço
      parameters:
        - name: uuid
          in: header
          description: UUID da esquina
          required: true
          type: string
          format: uuid
        - name: user
          in: header
          description: Identificador do usuário
          required: true
          type: string
          format: email
      tags:
        - Knowledge
      responses:
        '200':
          description: Usuário registrado
          schema:
            $ref: '#/definitions/Status'
        default:
          description: Erro inesperado
          schema:
            $ref: '#/definitions/Status'
definitions:
  Coordenadas:
    type: object
    required:
      - latitude
      - longitude
    properties:
      latitude:
        type: number
        format: double
        description: Latitude do local em graus decimais (-999.999999). Valores negativos indicam coordenadas ao Sul da linha do Equador.
      longitude:
        type: number
        format: double
        description: Longitude do local em graus decimais (-999.999999). Valores negativos indicam coordenadas à esquerda do meridiano de Greenwich.
      altitude:
        type: number
        format: double
        description: 'Altitude da esquina, em metros acima do nível do mar.'
  Rua:
    type: object
    required:
      - uuid
      - nome
    properties:
      uuid:
        type: string
        format: uuid
        description: Identificador único da rua
      nome:
        type: string
        description: Nome da rua
      largura:
        type: number
        format: integer
        description: 'Largura da rua, em metros'
  Esquina:
    type: object
    required:
      - uuid
      - ruaPrincipal
      - ruaSecundaria
    properties:
      uuid:
        type: string
        format: uuid
        description: Identificador único da esquina
      ruaPrincipal:
        type: object
        description: Rua principal do cruzamento
        $ref: '#/definitions/Rua'
      ruaSecundaria:
        type: object
        description: Rua secundária do cruzamento
        $ref: '#/definitions/Rua'
      posicao:
        $ref: '#/definitions/Coordenadas'
  Status:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
  CrossingStatus:
    type: object
    properties:
      uuidEsquina:
        type: string
        format: uuid
        description: UUID da esquina
      uuidRua:
        type: string
        format: uuid
        description: UUID da rua sobre a qual a informação do semáforo é válida
      last-update:
        description: Epoch time (ms) da última atualização dos dados
        type: integer
      seguroCruzar:
        type: boolean
        description: Valor lógico que indica se é seguro ou não atravessar essa rua
  Semaforos:
    description: Situação dos semáforos em um cruzamento
    type: object
    properties:
      status:
        type: array
        items:
          $ref: '#/definitions/CrossingStatus'
